import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/store/auth/AuthContext";
import Header from "@/components/Header/Header";
import Cart from "@/components/Cart/Cart";
import { CartContextProvider } from "@/store/cart/CartContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <CartContextProvider>
            <Header />
            {children}
            <Cart />
          </CartContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
