"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/store/auth/AuthContext";
import Header from "@/components/Header/Header";
import { useState } from "react";
import Cart from "@/components/Cart/Cart";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cartOpen, setCartOpen] = useState(false);
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <Header setCartOpen={setCartOpen} />
          {children}
          <Cart open={cartOpen} setOpen={setCartOpen} />
        </AuthContextProvider>
      </body>
    </html>
  );
}
